### PR TITLE
add ReinforcementLearningBase as dep

### PR DESCRIPTION
**Pull request by findmyway**
Do not merge until ReinforcementLearningBase get registered.

### CODE REVIEW

**Comment by jbrea** [comment]
ReinforcementLearningBase is now registered. I guess it should still be added to REQUIRE.

Regarding ```plotenv```: [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironmentClassicControl.jl/blob/921551b783841139b2e7210266d15aef56f7508e/src/cartpole.jl#L82) I display also the action taken and the end of the episode, which is why I had the funny function signature. Maybe this is not needed? Or is there a good alternative?

**Comment by findmyway** [comment]
Yeah, I'll fix it soon.

**Comment by findmyway** [comment]
let me think how to deal with the plotenv

**Comment by findmyway** [comment]
Hi @jbrea 

I've also modified ClassicControl.jl a little to make the interfaces unified.

See another two PR

https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironmentClassicControl.jl/pull/1
https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironmentGym.jl/pull/1

Comments are welcome. 😄

**Comment by jbrea** [comment]
Nice work!

I changed [ReinforcementLearningEnvironmentDiscrete](https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironmentDiscrete.jl/pull/1) in the same spirit (it still contains super old code that should be cleaned up eventually) and opened a PR in the [main package](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/16) to adapt to the changes.

@findmyway can you merge pull requests yourself in this org? I am not sure I set all the rights correctly.

**Comment by findmyway** [comment]
:+1: 

Sure, I have the right to merge PR in this org. :smile: 
I'll take a look of the PR in RL.jl soon.

**Pull request merged**
